feat: enhance CI workflow with frontend health check and rename backend check

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -94,7 +94,7 @@ jobs:
             docker compose up -d
             docker image prune -f
 
-      - name: Check API health
+      - name: Check backend API health
         run: |
           success=0
 
@@ -113,6 +113,25 @@ jobs:
             exit 1
           fi
 
+      - name: Check frontend health
+        run: |
+          success=0
+
+          for i in {1..10}; do
+            if curl -f https://${{ vars.DOMAIN }}; then
+              success=1
+              break
+            fi
+
+            echo "Frontend health check failed, retrying..."
+            sleep 5
+          done
+
+          if [ "$success" -ne 1 ]; then
+            echo "Frontend health check failed after 10 attempts, exiting..."
+            exit 1
+          fi
+
       - name: Success
         if: success()
         run: echo "Deployment successful ✅"
@@ -120,7 +139,3 @@ jobs:
       - name: Failure
         if: failure()
         run: echo "Deployment failed ❌"
-
-      - name: Clean up
-        if: always()
-        run: docker system prune -af
